### PR TITLE
fix prevent roles add event and dao roles add

### LINKED ISSUE #25: Role bot: add `DAO` role (all workers + leads + council)
SSIA, this role is important because it makes communication and coordination a lot easier and we don't currently have a role that does this so people have to tag various other roles.

### PR DESCRIPTION
**Pull request by HeinrichOlfert**
fix #25  #27  #28

### CODE REVIEW

File: Joystream-Role-Bot/src/controls/control.ts [hunk 1]
```diff
@@ -67,7 +73,7 @@ export const setMemberRole = async (client: Client): Promise<void> => {
     return;
   }
 
-  await api?.rpc.chain.subscribeNewHeads((header) => {
+  await api?.rpc.chain.subscribeNewHeads((header: any) => {
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:76]: Those `any` aren't needed. I get proper typing without those. Let's remove
CleanShot 2024-01-16 at 15 18 20@2x

File: Joystream-Role-Bot/src/controls/control.ts [hunk 2]
```diff
@@ -132,32 +154,65 @@ export const setMemberRole = async (client: Client): Promise<void> => {
     //   console.error("Error removing member roles:", error);
     // }
 
-    await discordMember.roles.add(RoleAddress.membershipLinked);
 
-    const roleUpdatePromises = qnMember.roles.map(async (memberRole) => {
-      const memberRoleGroupId = memberRole.groupId;
-      const mappedRoles = roleMap[memberRoleGroupId];
-      if (!mappedRoles) return;
+    const getRoles = discordMember.roles.cache.map((role: any) => role.id)
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:158]: Let's rename to `discordMemberRolesIds`

File: Joystream-Role-Bot/src/controls/control.ts [hunk 3]
```diff
@@ -132,32 +154,65 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
+        nowWorking[index].active = active;
+        nowWorking[index].lead = lead;
+        nowWorking[index].workingGroups = workingGroups;
+      } else {
+        nowWorking.push({ active, lead, workingGroups });
+      }
     });
 
+    let worker = false;
+    if (nowWorking.length !== 0) {
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:184]: `if` is not needed

File: Joystream-Role-Bot/src/controls/control.ts [hunk 4]
```diff
@@ -132,32 +154,65 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
+      nowWorking.map(async (work) => {
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:185]: Since we're not using return values in any way, let's replace `map` with `forEach`

File: Joystream-Role-Bot/src/controls/control.ts [hunk 5]
```diff
@@ -132,32 +154,65 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
 
-      if (!role) {
-        console.log(`<@&${roleId}> Role not found`);
-        return;
-      }
+    let nowWorking: GetWorkingState[] = [];
+
+    const roleUpdatePromises = qnMember.roles.map(async (memberRole: any) => {
+
+      const index = nowWorking.findIndex(data => data.workingGroups === memberRole.groupId)
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:168]: This logic doesn't resolve some of the issues reported. You are going through all the roles of the user ever and then overwriting with the most recent one. For example, here are my roles in DWG:
```
          {
            "status": {
              "__typename": "WorkerStatusTerminated"
            },
            "groupId": "distributionWorkingGroup",
            "isLead": false
          },
          {
            "status": {
              "__typename": "WorkerStatusActive"
            },
            "groupId": "distributionWorkingGroup",
            "isLead": false
          },
          {
            "status": {
              "__typename": "WorkerStatusTerminated"
            },
            "groupId": "distributionWorkingGroup",
            "isLead": false
          },
          {
            "status": {
              "__typename": "WorkerStatusActive"
            },
            "groupId": "distributionWorkingGroup",
            "isLead": false
          },
          {
            "status": {
              "__typename": "WorkerStatusTerminated"
            },
            "groupId": "distributionWorkingGroup",
            "isLead": false
          },
```
As you can see, last role is terminated, but I still have 2 active roles in DWG. You cannot only consider the last role.

File: Joystream-Role-Bot/src/controls/control.ts [hunk 6]
```diff
@@ -132,32 +154,65 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
 
-      const roleUpdatePromise =
-        memberRole.status.__typename === "WorkerStatusActive"
-          ? discordMember.roles.add(role)
-          : discordMember.roles.remove(role);
-      await roleUpdatePromise;
+      const active = memberRole.status.__typename === "WorkerStatusActive";
+      const lead = memberRole.isLead;
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:171]: Likewise for lead role, my last role can be for a worker but I can be a lead. I think you need to something like this:
1. Split all user roles by working group.
2. If any of the roles is still active, this member is a worker in that group
3. If any of the active roles is a lead role, that member is a lead

**Review by kdembler — CHANGES_REQUESTED** [review]

File: Joystream-Role-Bot/src/controls/control.ts (hunk 1 above)
Comment (HeinrichOlfert) [reply Joystream-Role-Bot/src/controls/control.ts:76]: okay

File: Joystream-Role-Bot/src/controls/control.ts [hunk 7]
```diff
@@ -132,32 +154,52 @@ export const setMemberRole = async (client: Client): Promise<void> => {
     //   console.error("Error removing member roles:", error);
     // }
 
-    await discordMember.roles.add(RoleAddress.membershipLinked);
 
-    const roleUpdatePromises = qnMember.roles.map(async (memberRole) => {
-      const memberRoleGroupId = memberRole.groupId;
-      const mappedRoles = roleMap[memberRoleGroupId];
+    const discordMemberAllRolesIds = discordMember.roles.cache.map((role) => role.id)
+    const roleAddressArray: string[] = Object.values(RoleAddress);
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:159]: What's the point of that? You can just do `RoleAddress[id]`, not need to use an array

File: Joystream-Role-Bot/src/controls/control.ts [hunk 8]
```diff
@@ -132,32 +154,52 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
+    const discordMemberRolesIds = discordMemberAllRolesIds.filter((item) => roleAddressArray.includes(item))
+
+    if (!discordMemberRolesIds.find((id: string) => id === RoleAddress.membershipLinked)) {
+      await discordMember.roles.add(linkRole);
+    }
+
+    const rolesMember = qnMember.roles.filter(group => group.status.__typename === "WorkerStatusActive");
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:166]: `qnMemberActiveRoles`

File: Joystream-Role-Bot/src/controls/control.ts [hunk 9]
```diff
@@ -132,32 +154,52 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
+
+    let worker = false;
+
+    let activeRoles: string[] = [];
+
+    rolesMember.forEach(async (work) => {
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:172]: `qnMemberRole`

File: Joystream-Role-Bot/src/controls/control.ts [hunk 10]
```diff
@@ -132,32 +154,52 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
+
+      const roleId = work.isLead ? leadRoleId : workerRoleId;
+
       const role = await guild.roles.fetch(roleId);
 
       if (!role) {
         console.log(`<@&${roleId}> Role not found`);
         return;
       }
+      if (!discordMemberRolesIds.find((id: string) => id === roleId)) discordMember.roles.add(role);
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:187]: Let's add braces to this `if`

File: Joystream-Role-Bot/src/controls/control.ts [hunk 11]
```diff
@@ -132,32 +154,52 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
+      activeRoles.push(roleId);
+      worker = true;
+    })
+
+    await Promise.all(rolesMember);
+
+    const terminatedRoles = discordMemberRolesIds.filter(item => !activeRoles.includes(item))
+    terminatedRoles.forEach(id => discordMember.roles.remove(id));
+    await Promise.all(terminatedRoles);
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:196]: `terminatedRoles` are not promises, you should do `const terminatedRolesPromises = terminatedRoles.map` and await those

File: Joystream-Role-Bot/src/controls/control.ts [hunk 12]
```diff
@@ -132,32 +154,52 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
-      const roleUpdatePromise =
-        memberRole.status.__typename === "WorkerStatusActive"
-          ? discordMember.roles.add(role)
-          : discordMember.roles.remove(role);
-      await roleUpdatePromise;
-    });
 
-    await Promise.all(roleUpdatePromises);
+    if ((worker || qnMember.isCouncilMember) && !discordMemberRolesIds.find((id: string) => id === RoleAddress.DAO)) discordMember.roles.add(daoRole)
+    if (!(worker || qnMember.isCouncilMember) && discordMemberRolesIds.find((id: string) => id === RoleAddress.DAO)) discordMember.roles.remove(daoRole)
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:200]: Let's add braces to the `if`s

File: Joystream-Role-Bot/src/controls/control.ts [hunk 13]
```diff
@@ -174,18 +216,19 @@ export const setMemberRole = async (client: Client): Promise<void> => {
...
         console.log(`<@&${specialRole.roleId}> Role not found`);
         return;
       }
 
-      const roleUpdatePromise = specialRole.isActive
-        ? discordMember.roles.add(role)
-        : discordMember.roles.remove(role);
-      await roleUpdatePromise;
+      if (specialRole.isActive && !discordMemberRolesIds.find((id: string) => id === specialRole.roleId)) discordMember.roles.add(role);
+      if (!specialRole.isActive && discordMemberRolesIds.find((id: string) => id === specialRole.roleId)) discordMember.roles.remove(role);
```
Comment (kdembler) [inline Joystream-Role-Bot/src/controls/control.ts:228]: Also here

**Review by kdembler — CHANGES_REQUESTED** [review]

File: Joystream-Role-Bot/src/controls/control.ts (hunk 7 above)
Comment (HeinrichOlfert) [reply Joystream-Role-Bot/src/controls/control.ts:159]: Image What this means is:

**Review by kdembler — APPROVED** [review]
